CREATE DATABASE ADIDAS_SALES;

CREATE TABLE IF NOT EXISTS BRONZE_ADIDAS_SALES (
	RETAILER VARCHAR(100),
	RETAILER_ID VARCHAR(20),
	INVOICE_DATE DATE,
	REGION VARCHAR(50),
	STATE VARCHAR(50),
	CITY VARCHAR(50),
	PRODUCT VARCHAR(50),
	PRICE_PER_UNIT NUMERIC(10, 2),
	UNITS_SOLD INTEGER,
	TOTAL_SALES NUMERIC(12, 2),
	OPERATING_PROFIT NUMERIC(12, 2),
	SALES_METHOD VARCHAR(20)
)

SELECT
	*
FROM
	BRONZE_ADIDAS_SALES;

CREATE TABLE IF NOT EXISTS SILVER_ADIDAS_SALES (
	RETAILER VARCHAR(100),
	RETAILER_ID VARCHAR(20),
	INVOICE_DATE DATE,
	REGION VARCHAR(50),
	STATE VARCHAR(50),
	CITY VARCHAR(50),
	PRODUCT VARCHAR(50),
	PRICE_PER_UNIT NUMERIC(10, 2),
	UNITS_SOLD INTEGER,
	TOTAL_SALES NUMERIC(12, 2),
	OPERATING_PROFIT NUMERIC(12, 2),
	SALES_METHOD VARCHAR(20),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

WITH
	BASE AS (
		SELECT
			RETAILER,
			RETAILER_ID,
			INVOICE_DATE,
			INITCAP(REGION) AS REGION,
			INITCAP(STATE) AS STATE,
			INITCAP(CITY) AS CITY,
			CASE
				WHEN PRODUCT = 'Men''s aparel' THEN 'Men''s Apparel'
				ELSE PRODUCT
			END AS PRODUCT,
			PRICE_PER_UNIT,
			COALESCE(UNITS_SOLD, 0) AS UNITS_SOLD,
			TOTAL_SALES,
			OPERATING_PROFIT,
			SALES_METHOD,
			CURRENT_TIMESTAMP AS CREATED_AT
		FROM
			BRONZE_ADIDAS_SALES
	),
	CALC AS (
		SELECT
			*,
			CASE
				WHEN PRICE_PER_UNIT IS NULL THEN TOTAL_SALES / NULLIF(UNITS_SOLD, 0)
				ELSE PRICE_PER_UNIT
			END AS FIXED_PRICE
		FROM
			BASE
	)
INSERT INTO
	SILVER_ADIDAS_SALES
SELECT
	RETAILER,
	RETAILER_ID,
	INVOICE_DATE,
	REGION,
	STATE,
	CITY,
	PRODUCT,
	FIXED_PRICE AS PRICE_PER_UNIT,
	UNITS_SOLD,
	FIXED_PRICE * UNITS_SOLD AS TOTAL_SALES,
	CASE
		WHEN FIXED_PRICE * UNITS_SOLD = TOTAL_SALES THEN OPERATING_PROFIT / 10
		ELSE OPERATING_PROFIT
	END AS OPERATING_PROFIT,
	SALES_METHOD,
	CREATED_AT
FROM
	CALC;

SELECT
	*
FROM
	SILVER_ADIDAS_SALES;

CREATE TABLE IF NOT EXISTS GOLD_ADIDAS_SALES (
	SALES_KEY BIGSERIAL PRIMARY KEY,
	DATE_KEY DATE NOT NULL REFERENCES DIM_DATE (DATE_KEY),
	RETAILER_KEY INTEGER NOT NULL REFERENCES DIM_RETAILER (RETAILER_KEY),
	LOCATION_KEY INTEGER REFERENCES DIM_LOCATION (LOCATION_KEY),
	PRODUCT_KEY INTEGER NOT NULL REFERENCES DIM_PRODUCT (PRODUCT_KEY),
	SALES_METHOD VARCHAR(30) NOT NULL,
	UNITS_SOLD INTEGER NOT NULL,
	PRICE_PER_UNIT NUMERIC(10, 2) NOT NULL,
	TOTAL_SALES NUMERIC(12, 2) NOT NULL,
	OPERATING_PROFIT NUMERIC(12, 2) NOT NULL,
	OPERATING_MARGIN NUMERIC(5, 2),
	COST_OF_GOODS_SOLD NUMERIC(12, 2),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DIM_DATE (
	DATE_KEY DATE PRIMARY KEY,
	YEAR INTEGER NOT NULL,
	QUARTER INTEGER NOT NULL,
	MONTH INTEGER NOT NULL,
	MONTH_NAME VARCHAR(20) NOT NULL,
	WEEK_OF_YEAR INTEGER NOT NULL,
	DAY_OF_MONTH INTEGER NOT NULL,
	DAY_OF_WEEK INTEGER NOT NULL,
	DAY_NAME VARCHAR(20) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
	DIM_DATE (
		DATE_KEY,
		YEAR,
		QUARTER,
		MONTH,
		MONTH_NAME,
		WEEK_OF_YEAR,
		DAY_OF_MONTH,
		DAY_OF_WEEK,
		DAY_NAME
	)
SELECT
	T.DAY AS DATE_KEY,
	EXTRACT(
		YEAR
		FROM
			T.DAY
	) AS YEAR,
	EXTRACT(
		QUARTER
		FROM
			T.DAY
	) AS QUARTER,
	EXTRACT(
		MONTH
		FROM
			T.DAY
	) AS MONTH,
	TO_CHAR(T.DAY, 'Month') AS MONTH_NAME,
	EXTRACT(
		WEEK
		FROM
			T.DAY
	) AS WEEK_OF_YEAR,
	EXTRACT(
		DAY
		FROM
			T.DAY
	) AS DAY_OF_MONTH,
	EXTRACT(
		ISODOW
		FROM
			T.DAY
	) AS DAY_OF_WEEK,
	TO_CHAR(T.DAY, 'Day') AS DAY_NAME
FROM
	GENERATE_SERIES(
		'2020-01-01'::DATE,
		'2025-12-31'::DATE,
		'1 day'::INTERVAL
	) AS T (DAY)
ON CONFLICT (DATE_KEY) DO NOTHING;

CREATE TABLE IF NOT EXISTS DIM_RETAILER (
	RETAILER_KEY SERIAL PRIMARY KEY,
	RETAILER_ID VARCHAR(40) NOT NULL,
	RETAILER_NAME VARCHAR(40),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DIM_PRODUCT (
	PRODUCT_KEY SERIAL PRIMARY KEY,
	PRODUCT_NAME VARCHAR(40),
	CATEGORY VARCHAR(40),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DIM_LOCATION (
	LOCATION_KEY SERIAL PRIMARY KEY,
	CITY VARCHAR(40),
	STATE VARCHAR(40),
	REGION VARCHAR(40),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
	DIM_RETAILER (RETAILER_ID, RETAILER_NAME)
SELECT DISTINCT
	S.RETAILER_ID,
	S.RETAILER
FROM
	SILVER_ADIDAS_SALES S
	LEFT JOIN DIM_RETAILER D ON S.RETAILER_ID = D.RETAILER_ID
	AND S.RETAILER = D.RETAILER_NAME
WHERE
	D.RETAILER_KEY IS NULL;

INSERT INTO
	DIM_PRODUCT (PRODUCT_NAME, CATEGORY)
SELECT DISTINCT
	S.PRODUCT,
	CASE
		WHEN S.PRODUCT LIKE '%Footwear%' THEN 'Footwear'
		WHEN S.PRODUCT LIKE '%Apparel%' THEN 'Apparel'
		ELSE 'Other'
	END AS CATEGORY
FROM
	SILVER_ADIDAS_SALES S
	LEFT JOIN DIM_PRODUCT D ON S.PRODUCT = D.PRODUCT_NAME
WHERE
	D.PRODUCT_KEY IS NULL;

INSERT INTO
	DIM_LOCATION (CITY, STATE, REGION)
SELECT DISTINCT
	S.CITY,
	S.STATE,
	S.REGION
FROM
	SILVER_ADIDAS_SALES S
	LEFT JOIN DIM_LOCATION D ON S.CITY = D.CITY
	AND S.STATE = D.STATE
	AND S.REGION = D.REGION
WHERE
	D.LOCATION_KEY IS NULL
	AND S.REGION IS NOT NULL;

TRUNCATE TABLE GOLD_ADIDAS_SALES
INSERT INTO
	GOLD_ADIDAS_SALES (
		DATE_KEY,
		RETAILER_KEY,
		LOCATION_KEY,
		PRODUCT_KEY,
		SALES_METHOD,
		UNITS_SOLD,
		PRICE_PER_UNIT,
		TOTAL_SALES,
		OPERATING_PROFIT,
		OPERATING_MARGIN,
		COST_OF_GOODS_SOLD
	)
SELECT
	D.DATE_KEY,
	R.RETAILER_KEY,
	L.LOCATION_KEY,
	P.PRODUCT_KEY,
	S.SALES_METHOD,
	S.UNITS_SOLD,
	S.PRICE_PER_UNIT,
	S.TOTAL_SALES,
	S.OPERATING_PROFIT,
	ROUND(
		100.0 * S.OPERATING_PROFIT / NULLIF(S.TOTAL_SALES, 0),
		2
	) AS OPERATING_MARGIN,
	(S.TOTAL_SALES - S.OPERATING_PROFIT) AS COST_OF_GOODS_SOLD
FROM
	SILVER_ADIDAS_SALES S
	JOIN DIM_DATE D ON S.INVOICE_DATE = D.DATE_KEY
	JOIN DIM_RETAILER R ON S.RETAILER_ID = R.RETAILER_ID
	AND S.RETAILER = R.RETAILER_NAME
	JOIN DIM_LOCATION L ON S.CITY = L.CITY
	AND S.STATE = L.STATE
	JOIN DIM_PRODUCT P ON S.PRODUCT = P.PRODUCT_NAME;

SELECT
	*
FROM
	DIM_LOCATION
ORDER BY
	STATE,
	CITY;

-------------------------------------------------------
